In [1]:
# Sample input
x_vals = [1.0, -1.0, 0.5]

# -------- Exponential (approx using series) --------
def exp(x):
    result = 1
    term = 1
    for i in range(1, 20):   # 20 terms approximation
        term = term * x / i
        result += term
    return result

# -------- Sigmoid --------
def sigmoid(x):
    return 1 / (1 + exp(-x))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

# -------- Tanh --------
def tanh(x):
    ex = exp(x)
    enx = exp(-x)
    return (ex - enx) / (ex + enx)

def tanh_derivative(x):
    t = tanh(x)
    return 1 - t*t

# -------- ReLU --------
def relu(x):
    if x > 0:
        return x
    else:
        return 0

def relu_derivative(x):
    if x > 0:
        return 1
    else:
        return 0

# -------- Leaky ReLU --------
def leaky_relu(x, alpha=0.01):
    if x > 0:
        return x
    else:
        return alpha * x

def leaky_relu_derivative(x, alpha=0.01):
    if x > 0:
        return 1
    else:
        return alpha

# -------- Softmax --------
def softmax(x_list):
    exp_vals = []
    for x in x_list:
        exp_vals.append(exp(x))
    
    total = 0
    for val in exp_vals:
        total += val

    result = []
    for val in exp_vals:
        result.append(val / total)
    
    return result

def softmax_derivative(x_list):
    s = softmax(x_list)
    jacobian = []

    for i in range(len(s)):
        row = []
        for j in range(len(s)):
            if i == j:
                row.append(s[i] * (1 - s[i]))
            else:
                row.append(-s[i] * s[j])
        jacobian.append(row)

    return jacobian

# -------- Output --------
print("Input:", x_vals)

print("\nSigmoid:")
for x in x_vals:
    print(sigmoid(x), "Derivative:", sigmoid_derivative(x))

print("\nTanh:")
for x in x_vals:
    print(tanh(x), "Derivative:", tanh_derivative(x))

print("\nReLU:")
for x in x_vals:
    print(relu(x), "Derivative:", relu_derivative(x))

print("\nLeaky ReLU:")
for x in x_vals:
    print(leaky_relu(x), "Derivative:", leaky_relu_derivative(x))

print("\nSoftmax:")
print(softmax(x_vals))

print("\nSoftmax Derivative (Jacobian):")
for row in softmax_derivative(x_vals):
    print(row)

Input: [1.0, -1.0, 0.5]

Sigmoid:
0.7310585786300049 Derivative: 0.19661193324148185
0.2689414213699951 Derivative: 0.19661193324148185
0.6224593312018547 Derivative: 0.23500371220159447

Tanh:
0.7615941559557649 Derivative: 0.41997434161402614
-0.7615941559557649 Derivative: 0.41997434161402614
0.4621171572600098 Derivative: 0.7864477329659274

ReLU:
1.0 Derivative: 1
0 Derivative: 0
0.5 Derivative: 1

Leaky ReLU:
1.0 Derivative: 1
-0.01 Derivative: 0.01
0.5 Derivative: 1

Softmax:
[0.5740969929676947, 0.07769557914857061, 0.34820742788373477]

Softmax Derivative (Jacobian):
[0.2445096356331454, -0.04460479835607791, -0.19990483727706754]
[-0.04460479835607791, 0.07165897612933882, -0.02705417777326091]
[-0.19990483727706754, -0.02705417777326091, 0.2269590150503284]


In [2]:
import numpy as np

# Input
x = np.array([1.0, -1.0, 0.5])

# -------- Sigmoid --------
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    s = sigmoid(x)
    return s * (1 - s)

# -------- Tanh --------
def tanh(x):
    return np.tanh(x)

def tanh_derivative(x):
    return 1 - np.tanh(x)**2

# -------- ReLU --------
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

# -------- Leaky ReLU --------
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)

def leaky_relu_derivative(x, alpha=0.01):
    return np.where(x > 0, 1, alpha)

# -------- Softmax --------
def softmax(x):
    exp_x = np.exp(x - np.max(x))   # stability trick
    return exp_x / np.sum(exp_x)

def softmax_derivative(x):
    s = softmax(x).reshape(-1,1)
    return np.diagflat(s) - np.dot(s, s.T)

# -------- Output --------
print("Input:", x)

print("\nSigmoid:", sigmoid(x))
print("Sigmoid Derivative:", sigmoid_derivative(x))

print("\nTanh:", tanh(x))
print("Tanh Derivative:", tanh_derivative(x))

print("\nReLU:", relu(x))
print("ReLU Derivative:", relu_derivative(x))

print("\nLeaky ReLU:", leaky_relu(x))
print("Leaky ReLU Derivative:", leaky_relu_derivative(x))

print("\nSoftmax:", softmax(x))
print("Softmax Derivative (Jacobian):\n", softmax_derivative(x))

Input: [ 1.  -1.   0.5]

Sigmoid: [0.73105858 0.26894142 0.62245933]
Sigmoid Derivative: [0.19661193 0.19661193 0.23500371]

Tanh: [ 0.76159416 -0.76159416  0.46211716]
Tanh Derivative: [0.41997434 0.41997434 0.78644773]

ReLU: [1.  0.  0.5]
ReLU Derivative: [1 0 1]

Leaky ReLU: [ 1.   -0.01  0.5 ]
Leaky ReLU Derivative: [1.   0.01 1.  ]

Softmax: [0.57409699 0.07769558 0.34820743]
Softmax Derivative (Jacobian):
 [[ 0.24450964 -0.0446048  -0.19990484]
 [-0.0446048   0.07165898 -0.02705418]
 [-0.19990484 -0.02705418  0.22695902]]
